### ISSUE TITLE
SHOULD omit `.DS_Store` files

### ISSUE THREAD

**Issue by ch-ntz** [pseudozach/redphone#1]
Omit `.DS_Store` files using `.gitignore`

Here's a "generic" `.gitignore` configuration I use for omitting many standard os/editor files from inclusion in my repositories:

https://gist.github.com/chantzlarge/da4b4e364d6aff6a8ed02ca2a1d6b77a

**Comment by pseudozach** [comment]
yes, that was annoying. I removed it with https://github.com/pseudozach/redphone/commit/f5819aeb58ba9ad17df50dc5c289c5bc504aaab2
thanks for the gist
